{"name": "test_login_001", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0", "trace": "self = <scripts.test_login.TestLogin object at 0x00000192882B1850>\n\n    def test_login_001(self):\n>       assert 0\nE       assert 0\n\nscripts\\test_login.py:4: AssertionError"}, "start": 1616418179073, "stop": 1616418179073, "uuid": "4f48ba7b-6795-434a-81d3-a4e44ca7305a", "historyId": "14ed3a6f43764b7f6f01338819c9c297", "testCaseId": "61fd03ca604429f4bd9d857ac5f51598", "fullName": "scripts.test_login.TestLogin#test_login_001", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-6D0RDNU"}, {"name": "thread", "value": "9372-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test_login"}]}